w <- getwd()
setwd('data-raw')
zip(zipfile = 'dukehw.zip', files = dir(path = 'example', full.names = T, recursive = T))
dukehw <- readBin( file('dukehw.zip', 'rb'), 'raw', n = 10^13)
file.remove('dukehw.zip')
setwd(w)
devtools::use_data(dukehw, overwrite = T)
closeAllConnections()
rm(list = ls())
