globalVariables(names = c('Year','Month', 'Day', 'Hour', 'Minute', 'Second',
                          'HHMMSS','DOY', 'Date', 'DateTime', 'YearDOY',
                          'ID', 'Label', 'x', 'y', 'z', '.', 'archive',
                          'mainDataPath', 'middayListPath', 'newpath', 'path', 'filenames',
                          'band', 'blackness',  'conT', 'dukehw', 'empty',
                          'GRVI', 'exG',
                          'gbR', 'grR', 'rbR',
                          'red', 'green', 'blue',
                          'bcc', 'bcc05', 'bcc10', 'bcc25', 'bcc75', 'bcc90', 'bcc95',
                          'gcc', 'gcc05', 'gcc10', 'gcc25', 'gcc75', 'gcc90', 'gcc95',
                          'rcc', 'rcc05', 'rcc10', 'rcc25', 'rcc75', 'rcc90', 'rcc95'))
